### ISSUE TITLE
Why can't I get the results?

### ISSUE THREAD

**Issue by emanonzzz** [joncrangle/sketchybar-system-stats#16]
<img width="1232" alt="image" src="https://github.com/user-attachments/assets/020a999e-3a8e-408c-8a9c-b80e59dadabf">

**Comment by joncrangle** [comment]
If you'd like to see the output in your terminal, you can run `stats_provider` with the `--verbose` flag added and you'll see the message log. The messages are sent to `sketchybar` using inter-process mach messages, so that's why there isn't currently any output in the terminal.

Based on your issue, I think I'll add a log message that stats_provider is running when the program is started, just so it's clear that it's running and not hanging or crashed. I hadn't thought of that since most of the time it's running in the background for me after being initiated by `sketchybar`.

**Comment by emanonzzz** [comment]
> If you'd like to see the output in your terminal, you can run `stats_provider` with the `--verbose` flag added and you'll see the message log. The messages are sent to `sketchybar` using inter-process mach messages, so that's why there isn't currently any output in the terminal.
> 
> Based on your issue, I think I'll add a log message that stats_provider is running when the program is started, just so it's clear that it's running and not hanging or crashed. I hadn't thought of that since most of the time it's running in the background for me after being initiated by `sketchybar`.根据您的问题，我认为在程序启动时添加一条日志消息，表明 stats_provider 

Thanks, I've got the results I wanted at sketchybar.
